apiVersion: batch/v1
kind: CronJob
metadata:
  name: tfl-kubemlpr
spec:
  schedule: "*/1 * * * *"  # This runs the job every 5 minutes
  successfulJobsHistoryLimit: 3  # Keep only the last 3 successful jobs
  failedJobsHistoryLimit: 1      # Keep only 1 failed job
  jobTemplate:
    spec:
      backoffLimit: 4  # This controls the number of retries for the job
      template:
        spec:
          containers:
          - name: forecasteml
            image: jayakatrela/tfl-kubemlpr:latest
          restartPolicy: Never
